// global variables start
const $onClickRoll5 = $('.onClickRoll5');  
const $onClickRoll4 = $('.onClickRoll4');
const $onClickRoll3 = $('.onClickRoll3');  
const $onClickRoll2 = $('.onClickRoll2');
const $onClickRoll1 = $('.onClickRoll1');
// global variables end

//create a random number each time function is called.
function grabRandomNum() {
  let randomNum = Math.floor(Math.random() * 6) + 1; //number from 1-6
  return randomNum;
}
//DOM click event listeners that will generate the right number of 1-6 numbers according to the button clicked. 

//generates 5 random numbers from 1-6 and pastes them into the DOM. 
$onClickRoll5.click(function(){//creates the click function.
    //selects the element with the correct ID and pastes in new DOM elements including the random number generated by the RandomNum() function. 
    $('.dice-button').html('<h4 class="rolled-title">You rolled:</h4><button>' + grabRandomNum() + '</button><button>' + grabRandomNum() + '</button><button>' + grabRandomNum() + '</button><button>' + grabRandomNum() + '</button><button>' + grabRandomNum() + '</button>');
});

//generates 4 random numbers from 1-6 and pastes them into the DOM. 
$onClickRoll4.click(function(){//creates the click function.
    //selects the element with the correct ID and pastes in new DOM elements including the random number generated by the RandomNum() function. 
    $('.dice-button').html('<h4 class="rolled-title">You rolled:</h4><button>' + grabRandomNum() + '</button><button>' + grabRandomNum() + '</button><button>' + grabRandomNum() + '</button><button>' + grabRandomNum() + '</button>');
  });

//generates 3 random numbers from 1-6 and pastes them into the DOM. 
$onClickRoll3.click(function(){//creates the click function.
    //selects the element with the correct ID and pastes in new DOM elements including the random number generated by the RandomNum() function. 
    $('.dice-button').html('<h4 class="rolled-title">You rolled:</h4><button>' + grabRandomNum() + '</button><button>' + grabRandomNum() + '</button><button>' + grabRandomNum() + '</button>');
});

//generates 2 random numbers from 1-6 and pastes them into the DOM. 
$onClickRoll2.click(function(){//creates the click function.
    //selects the element with the correct ID and pastes in new DOM elements including the random number generated by the RandomNum() function. 
    $('.dice-button').html('<h4 class="rolled-title">You rolled:</h4><button>' + grabRandomNum() + '</button><button>' + grabRandomNum() + '</button>');
  });

//generates 1 random number from 1-6 and pastes it into the DOM. 
$onClickRoll1.click(function(){//creates the click function.
    //selects the element with the correct ID and pastes in new DOM elements including the random number generated by the RandomNum() function. 
    $('.dice-button').html('<h4 class="rolled-title">You rolled:</h4><button>' + grabRandomNum() + '</button>');
});
